# SPDX-FileCopyrightText: Copyright 2022-2026 Arm Limited and/or its
# affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Build NUCLEO-H563ZI Debug HIL
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./vcpkg-configuration.json"
          cache: "NUCLEO-H563ZI"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget python3-dev python3-venv python3-tk \
          xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

      - name: Create a Python virtual environment
        run: |
          echo "Create a new virtual environment in /home/runner/zephyrproject/ "
          python -m venv /home/runner/zephyrproject/.venv
          echo "/home/runner/zephyrproject/.venv/bin" >> $GITHUB_PATH

      - name: Install west
        continue-on-error: true    
        run: |
          # 1. Upgrade pip
          python -m pip install --upgrade pip

          # 2. Change to the zephyrproject directory
          cd /home/runner/zephyrproject

          # 3. Install west
          pip install west

          # 4. Show where west gets installed
          which west

          # 5. Initialize Zephyr workspace
          west init

          # 6. Update Zephyr workspace
          west -v update

      - name: Cache the Zephyrproject
        uses: actions/cache@v5
        with:
          key: install-west
          path: /home/runner/zephyrproject

      - name: Install Zephyr Python dependencies
        run: |
          # 1.  Change to the zephyrproject directory
          cd /home/runner/zephyrproject

          # 2. Activate the virtual environment
          source ./.venv/bin/activate

          # 3. Install west packages
          west packages pip --install

      - name: Set Zephyr environment
        run: |
          echo "ZEPHYR_BASE=/home/runner/zephyrproject/zephyr" >> $GITHUB_ENV
          echo "VIRTUAL_ENV=/home/runner/zephyrproject/.venv" >> $GITHUB_ENV
          echo "PATH=/home/runner/zephyrproject/.venv/bin:$PATH" >> $GITHUB_ENV

      - name: Build the NUCLEO-H563ZI HIL binary
        run: |
          # 1. Activate the virtual environment
          source /home/runner/zephyrproject/.venv/bin/activate

          # 2. Build binary
          cbuild zephyr.csolution.yml --active NUCLEO-H563ZI@HIL --packs

      - name: Upload output NUCLEO-H563ZI_Debug_HIL
        uses: actions/upload-artifact@v7
        with:
          name: NUCLEO-H563ZI@Debug_HIL
          path: |
            ./out/
          include-hidden-files: true
